#!/usr/bin/env bash

#!/usr/bin/env bash
set -ex

# Disable xdebug in production environment
xdebug_config=/usr/local/etc/php/conf.d/xdebug.ini
if [ -f $xdebug_config ] && [ "$SYMFONY_ENV" == "prod" ]; then
    rm $xdebug_config
fi
# Prepare application
bin/console cache:warmup

# Start Application
php-fpm --allow-to-run-as-root
