version: "2"

services:
  app:
    volumes:
      - './..:/app'
      - './php/entrypoint:/app/entrypoint'

  nginx:
    environment:
      - VIRTUAL_HOST=chats.docker
      - VIRTUAL_PORT=80
      - EXPOSE_APIDOC=true

  apidoc:
    image: humangeo/aglio
    volumes:
      - './../config/docs:/docs:ro'
    command: ['--server', '-i', '/docs/index.md', '-h', '0.0.0.0', '-p', '3000']
