services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Chat\Controller\:
        resource: '../src/Controller'
        public: true
        tags: ['controller.service_arguments']
